### ISSUE TITLE
Clear cache by key - partial parameters?

### ISSUE THREAD

**Issue by ahi-el** [pub-comp/caching#78]
Hi, I have the following method

![image](https://github.com/pub-comp/caching/assets/37062459/594943c2-5234-47f4-92ed-633bb0679834)

I'd like to be able to refresh the cache by two fields - the cache name, and a parameter name/value. 
The current cache refresh mechanism requires to know the exact method that's being called, the class name, the EXACT parameter combination used - it causes for extremely high coupling between the code that would like to refresh the cache and the code that uses it.

What do you think about allowing for cache refresh by only part of the key signature?

![image](https://github.com/pub-comp/caching/assets/37062459/ceec4b1b-0369-4554-88ca-0ea23603d048)

I'd like to use only a few small parts of the cache key - namely, the first parameter value

**Comment by DannyVarod** [comment]
It seems wiser to enumerate the enum and build the possible cache keys via CacheKey.GetKey() and then clear these keys from the cache. I have used this approach easily in the past to accomplish this exact requirement.

The cache key is a string and impl what you are suggesting would require dangerous pattern matching of the cache key string.
